# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('selsta101', '0005_auto_20170327_1147'),
    ]

    operations = [

        # # Remove media.code duplications
        # migrations.RunSQL('DELETE FROM selsta101_instagrammedia a '
        #                   'WHERE a.id <> (SELECT min(b.id) FROM selsta101_instagrammedia b '
        #                   'WHERE a.code = b.code);'),

        migrations.AlterField(
            model_name='instagrammedia',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),

        migrations.AlterField(
            model_name='instagrammedia',
            name='code',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),

        migrations.AlterField(
            model_name='instagrammedia',
            name='owner_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='instagrammedia',
            name='source_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='dailyrank',
            unique_together=set([('date', 'rank'), ('date', 'media')]),
        ),
    ]
