# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsta101', '0006_auto_20170410_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrank',
            name='turn',
            field=models.IntegerField(db_index=True, default=-1),
        ),
        migrations.AlterUniqueTogether(
            name='dailyrank',
            unique_together=set([('date', 'turn', 'media'), ('date', 'turn', 'rank')]),
        ),
    ]
