version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq

  django_nginx:
    image: selstagram-django:0.1
    container_name: django01
    ports:
      - "8000:80"
    depends_on:
      - rabbitmq
