version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq

  django_nginx:
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq//
    image: selstagram-django:0.1
    container_name: django01
    ports:
      - "80:80"
    links:
      - rabbitmq
