version: '3'
services:
  django_nginx:
    env_file:
      - web/environment_variables
    image: artify/selstagram-server:0.1
    container_name: django01
    ports:
      - "80:80"
    external_links:
      - postgres

