# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljob',
            name='limit_count',
            field=models.IntegerField(default=-1),
        ),
    ]
